version: '3'
services:
  data-loader-minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: AKIAIOSFODNN7EXAMPLE
      MINIO_ROOT_PASSWORD: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
      MINIO_REGION: eu-west-2
    ports:
      - "9001:9002"
    entrypoint: sh
    volumes:
      - ".minio:/data"
    command: ['-c', 'mkdir -p /data/my-bucket && minio server /data --console-address ":9002"']
  data-loader:
    build:
      context: ./
      dockerfile: ./compose/Dockerfile
    env_file: .env
    command: /fds_loader/run-loader.sh
    platform: "linux/x86_64"
    links:
      - data-loader-minio
    volumes:
      - ./data:/data
